version: "3"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    container_name: hal_chinema_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hal_chinema
    networks:
      - hal_chinema

networks:
  hal_chinema:
